language: go

go:
    # 1.5 is "undefined: http.MethodGet"
    # - 1.5
    - 1.8
    - 1.9
    - "1.10"
    - 1.11
    - "1.10.x"

script:
    - go get github.com/pkg/errors
    - go test -cover -v ./...
